// <auto-generated />
using System;
using CompraProgramada.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramada.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305153751_AddPrecoMedioColumn")]
    partial class AddPrecoMedioColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CestaRecomendada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa")
                        .HasComment("cesta ativa");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<DateTime>("DataDesativacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_desativacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome")
                        .HasComment("nome cesta");

                    b.HasKey("Id");

                    b.ToTable("cesta", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo")
                        .HasComment("usuário ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf")
                        .HasComment("cpf do usuário");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_adesao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email")
                        .HasComment("email usuário");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome")
                        .HasComment("nome usuário");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_anterior")
                        .HasComment("valor anterior de compra");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_mensal")
                        .HasComment("valor mensal de compra");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ComposicaoCesta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CestaId")
                        .HasColumnType("int")
                        .HasColumnName("cesta_id")
                        .HasComment("identificador cesta");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("percentual")
                        .HasComment("percentual ocupante na cesta");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticker")
                        .HasComment("ativo");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("composicao_cesta", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ComposicaoCotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CotacaoId")
                        .HasColumnType("int")
                        .HasColumnName("cotacao_id")
                        .HasComment("identificador composição de cotação");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("preco_fechamento")
                        .HasComment("preço do fechamento do ativo");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticker")
                        .HasComment("identificação ativo");

                    b.HasKey("Id");

                    b.HasIndex("CotacaoId");

                    b.ToTable("composicao_cotacao", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaGrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero_conta")
                        .HasComment("número conta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo")
                        .HasComment("tipo conta");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("conta_grafica", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero_conta")
                        .HasComment("número conta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo")
                        .HasComment("tipo conta");

                    b.HasKey("Id");

                    b.ToTable("conta_master", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Cotacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPregao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_pregao")
                        .HasComment("data do pregão");

                    b.HasKey("Id");

                    b.ToTable("cotacao", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CustodiaFilhote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaGraficaId")
                        .HasColumnType("int")
                        .HasColumnName("conta_grafica_id")
                        .HasComment("identificador conta");

                    b.Property<decimal>("PrecoMedio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(65,30)")
                        .HasDefaultValue(0m)
                        .HasColumnName("preco_medio")
                        .HasComment("custo médio ponderado de compra");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("quantidade")
                        .HasComment("quantidade comprado");

                    b.Property<string>("Ticker")
                        .HasColumnType("longtext")
                        .HasColumnName("ticker")
                        .HasComment("ativo");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.ToTable("custodia_filhote", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CustodiaMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaMasterId")
                        .HasColumnType("int")
                        .HasColumnName("conta_master_id")
                        .HasComment("identificador conta");

                    b.Property<int>("QuantidadeResiduo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("quantidade_residuo")
                        .HasComment("quantidade de ativos que sobraram");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticker")
                        .HasComment("ativo");

                    b.HasKey("Id");

                    b.HasIndex("ContaMasterId");

                    b.ToTable("custodia_master", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Distribuicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaGraficaId")
                        .HasColumnType("int")
                        .HasColumnName("conta_grafica_id")
                        .HasComment("identificador conta cliente");

                    b.Property<int>("OrdemCompraId")
                        .HasColumnType("int")
                        .HasColumnName("ordem_compra_id")
                        .HasComment("identificador ordem de compra");

                    b.Property<int>("QuantidadeAlocada")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_alocada")
                        .HasComment("quantidade alocada na custodia");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticker")
                        .HasComment("ativo comprado");

                    b.Property<decimal>("ValorOperacao")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_operacao")
                        .HasComment("resultado financeiro da fatia");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("distribuicao", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.HistoricoExecucaoMotor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_execucao")
                        .HasComment("data que foi executado");

                    b.Property<DateTime>("DataReferencia")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_referencia")
                        .HasComment("data que deveria ser executada");

                    b.Property<bool>("Executado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("executado")
                        .HasComment("compra feita");

                    b.HasKey("Id");

                    b.ToTable("historico_execucao_motor", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.OrdemCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data")
                        .HasComment("data da compra");

                    b.Property<decimal>("PrecoExecucao")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("preco_execucao")
                        .HasComment("preço da compra executada");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade")
                        .HasComment("quantidade total de ativos comprados");

                    b.Property<int>("QuantidadeLotePadrao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("quantidade_lote_padrao")
                        .HasComment("quantos multiplos de 100 foram comprados");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticker")
                        .HasComment("ativo comprado");

                    b.HasKey("Id");

                    b.ToTable("ordem_compra", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ComposicaoCesta", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.CestaRecomendada", "Cesta")
                        .WithMany("ComposicaoCesta")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cesta");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ComposicaoCotacao", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.Cotacao", "Cotacao")
                        .WithMany("ComposicaoCotacao")
                        .HasForeignKey("CotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cotacao");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("CompraProgramada.Domain.Entity.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CustodiaFilhote", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.ContaGrafica", "ContaGrafica")
                        .WithMany("CustodiaFilhotes")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CustodiaMaster", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.ContaMaster", "ContaMaster")
                        .WithMany("CustodiaMasters")
                        .HasForeignKey("ContaMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaMaster");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Distribuicao", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.ContaGrafica", "ContaGrafica")
                        .WithMany("Distribuicoes")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompraProgramada.Domain.Entity.OrdemCompra", "OrdemCompra")
                        .WithMany("Distribuicoes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");

                    b.Navigation("OrdemCompra");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CestaRecomendada", b =>
                {
                    b.Navigation("ComposicaoCesta");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Cliente", b =>
                {
                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaGrafica", b =>
                {
                    b.Navigation("CustodiaFilhotes");

                    b.Navigation("Distribuicoes");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaMaster", b =>
                {
                    b.Navigation("CustodiaMasters");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Cotacao", b =>
                {
                    b.Navigation("ComposicaoCotacao");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.OrdemCompra", b =>
                {
                    b.Navigation("Distribuicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
