// <auto-generated />
using System;
using CompraProgramada.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraProgramada.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301182302_ClienteScheme")]
    partial class ClienteScheme
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo")
                        .HasComment("usuário ativo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("cpf")
                        .HasComment("cpf do usuário");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_adesao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email")
                        .HasComment("email usuário");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome")
                        .HasComment("nome usuário");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_mensal")
                        .HasComment("valor mensal de compra");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaGrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("numero_conta")
                        .HasComment("número conta");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo")
                        .HasComment("tipo conta");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("conta_grafica", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CustodiaFilhote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasComment("identificador");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaGraficaId")
                        .HasColumnType("int")
                        .HasColumnName("conta_grafica_id")
                        .HasComment("identificador conta");

                    b.Property<int>("Quantidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("quantidade")
                        .HasComment("quantidade comprado");

                    b.Property<string>("Ticker")
                        .HasColumnType("longtext")
                        .HasColumnName("ticker")
                        .HasComment("ativo");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId")
                        .IsUnique();

                    b.ToTable("custodia_filhote", (string)null);
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaGrafica", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.Cliente", "Cliente")
                        .WithOne("ContaGrafica")
                        .HasForeignKey("CompraProgramada.Domain.Entity.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.CustodiaFilhote", b =>
                {
                    b.HasOne("CompraProgramada.Domain.Entity.ContaGrafica", "ContaGrafica")
                        .WithOne("CustodiaFilhote")
                        .HasForeignKey("CompraProgramada.Domain.Entity.CustodiaFilhote", "ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.Cliente", b =>
                {
                    b.Navigation("ContaGrafica");
                });

            modelBuilder.Entity("CompraProgramada.Domain.Entity.ContaGrafica", b =>
                {
                    b.Navigation("CustodiaFilhote")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
